language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "mgT/5UEbR1pghwNwCFQR8xMma9uN3DctVGEOn1CjCwyXhDtsx6s0Yq4eO4OF3sTpsuHdIwxxcRUxXE7OA/iRm6UAv0xCsKjD4V8Wz7BGY3EEuUsKqK4F+p4UeL1kwHQJaYgw7UfZoNwPo8Ck+UkJ6p4qh5mFG3HZDMBRIDeIaXnKNwT89wUnid1qp76Mz1aHb+Cxmy767Vy1U9grUYyeYKWWRQj4pz5bmp8shbt0P3qVcOAYS7sr9NX3JGEnSUMBrW3a9rNIAzFKJfEmbm/tzaP04Z8uofYVCR9Qql8d/a6ubOb16LcZXq170/A9rlPk8NWnV9KLva8xT9Mr7us3zC7a1Xb3lCZJ1d3HcBVj5b2TedrpLGa+p7KBC5yn8c1vRWJa2q2JIN++QVrrmq2v8Hod9y12f1eFwOcE7cNfTgSXMs5Nq34zjcznP4daiCDwiUdpBKugp2sFFVBhCd2cu0Up45Cj87JG172L5wN2pTlBLAMoaaNu9PblDbLeoS+rCmRRhFGeLoQ7jFQYKDt+oPNuOdx3T0dnGFq25PqnZSS9qJt7EAFLZezhqc1Aamx5ZZFn+le1PDjzIhBwfVFgJLBDCUXnfYT2jAoQb6g8d1H8UiJNp1xWq0MBYxkdcyQTAAi8H+Z+wgIeLSgfQ0BVoXveQQqu8UAy1FYhBYyLtg0="
