language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "emQGoTu+1k2SonCWROIDvdS9NIbmuP9m84db3I3nRhBP90l13E9gH7cm1cOoBHdvBgFAa6V3nWTVs2PgDJpuMIPQ8bDpDFEiQQulzq2vYh98h1vt8RAMbITH2AFGeaWz5G0NObx8zzSsTTITiX9AeuwsR8G0e8whyOVyLmAe1QXQwPsMDWH0/dq95YdrFpThJe2TZ/d4gSkHeVpgHSJ6pm3X1PD36JDCtfMjBGacjDIc1ecZPYO96eZrBdER/R3nuD7TaTd59W80uX17Kh058iHiWutB0njfwKx7I00xVshMBecKhnwiBVWjQ2kkxpD3RDC7kXAlgbCVDgPrT6rJUhDX7mNDR8rU9Q5DY8ixhCMrV+dSVAjJVPQu6RVwwfVOFcORgFO/nxBto2UpezL9x3smz8jC3bSwfGTpyJ/KstVEUnVO4eY5ewlMYw7lYqit8AblvsfTviTm0en94GUjTUgAqjMyM51ynVIqF5Azas/XyzGlPIplW8lkqvcaBcpLjA0Q7SDyQxgw0UQue6/q7z+FXz7G9i1m6bpYmnHISJicj2WPyeeVB2qn9I1vAbJMOA6K1rgwFZEYz158w2orBBtSSopOXE9O6xUoEVVlNx0b+PFcODWdznBY7YJz3sWlM+DcSmzEChNu6OzhbI2IWfr7IAhGqJmm/45hn9hRPvU="
